#!/bin/bash

/opt/splunkforwarder/bin/splunk start

# aws s3 cp s3://.../.../etc.tgz ./
# tar xvfz ./etc.tgz -C $SPLUNK_HOME
# aws s3 cp s3://.../.../splunkclouduf.spl ./
# /opt/splunkforwarder/bin/splunk install app splunkclouduf.spl -auth admin:password

/opt/splunkforwarder/bin/splunk restart

sleep 5

/opt/splunkforwarder/bin/splunk status

tail -f /dev/null