#!/bin/bash

echo "Starting Splunk Universal Forwarder"

/opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt

# aws s3 cp s3://.../.../splunkclouduf.spl ./
# /opt/splunkforwarder/bin/splunk install app splunkclouduf.spl -auth admin:password

/opt/splunkforwarder/bin/splunk restart
