services:
    dotcom:
        build:
            context: ../
            dockerfile: ./deploy/dotcom/dev/Dockerfile
        env_file:
            - ../.env
        depends_on:
            redis:
                condition: service_started
        environment:
            - MIX_ENV=dev
            - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            - PORT=4001
            - REDIS_HOST=10.0.0.4
            - REDIS_PORT=6379
            - REDIS_STANDALONE=true
            - NAME=dotcom@10.0.0.1
            - WEBPACK_PORT=8091
        expose:
            - 4001
        ports:
            - 4001:4001
            - 8091:8091
        healthcheck:
            test: curl --fail http://localhost:4002/_health || exit 1
            interval: 10s
            retries: 5
            start_period: 120s
            timeout: 10s
        volumes:
            - ../:/app
            - /app/_build
            - /app/deps
            - /app/assets/node_modules
        networks:
            dotcom_network:
                ipv4_address: 10.0.0.1
    libretranslate:
        image: libretranslate/libretranslate
        environment:
            - LT_LOAD_ONLY=en,es
        ports:
            - 9999:5000
        healthcheck:
            test: curl --fail http://localhost:5000/languages || exit 1
            interval: 10s
            retries: 5
            start_period: 15s
            timeout: 10s
        networks:
            dotcom_network:
                ipv4_address: 10.0.0.2
    livebook:
        image: ghcr.io/livebook-dev/livebook:nightly
        environment:
            - LIVEBOOK_DEFAULT_RUNTIME=attached:dotcom@10.0.0.1:foobarbaz
            - LIVEBOOK_PASSWORD=foobarbazfoobarbaz
        ports:
            - 8888:8080
            - 8081:8081
        networks:
            dotcom_network:
                ipv4_address: 10.0.0.3
    redis:
        image: redis:7.2.4
        networks:
            dotcom_network:
                ipv4_address: 10.0.0.4
networks:
    dotcom_network:
        driver: bridge
        ipam:
            config:
                - subnet: 10.0.0.0/24
                  gateway: 10.0.0.254
