# Reusable action for retrieving from cache or compiling
#
# Usage:
# - uses: ./.github/actions/build-app

name: Build and cache application
description: "Build Dotcom assets and compile application"

runs:
  using: "composite"
  steps:
  - name: Cache _build
    uses: actions/cache@v3
    with:
      path: |
        _build
        apps/site/react_renderer/dist/app.js
      key: ci-application-cache-${{ github.sha }}
    id: build-cache
 
  - uses: ./.github/actions/setup-all
    if: steps.build-cache.outputs.cache-hit != 'true'

  - name: Compile application (if needed)
    shell: bash
    run: |
      mix compile.assets
      mix compile --all-warnings
    if: steps.build-cache.outputs.cache-hit != 'true'
