#!/bin/bash

/opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt > /dev/null

# aws s3 cp s3://.../.../splunkclouduf.spl ./

/opt/splunkforwarder/bin/splunk install app splunkclouduf.spl -auth admin:password > /dev/null
/opt/splunkforwarder/bin/splunk restart > /dev/null

node ./monitor/all-scenarios.js
