import Config

config :dotcom, :cache, Dotcom.Cache.Multilevel

# configured separately so that we can have the health check not require
# SSL
config :dotcom, :secure_pipeline,
  force_ssl: [
    host: nil,
    rewrite_on: [:x_forwarded_proto]
  ]

config :dotcom, DotcomWeb.Endpoint,
  # Enable IPv6 and bind on all interfaces.
  # Set it to  {0, 0, 0, 0, 0, 0, 0, 1} for local network only access.
  # See the documentation on https://hexdocs.pm/bandit/Bandit.html#t:options/0
  # for details about using IPv6 vs IPv4 and loopback vs public addresses.m the server machine.
  http: [
    ip: :inet6,
    thousand_island_options: [
      num_acceptors: 2_048,
      num_connections: 32_768
    ],
    http_options: [
      compress: true
    ],
    http_1_options: [
      max_header_length: 16_384,
      max_request_line_length: 16_384
    ]
  ],

  # Finally, we also include the path to a manifest
  # containing the digested version of static files. This
  # manifest is generated by the mix phx.digest task
  # which you typically run after static files are built.
  cache_static_manifest: "priv/static/cache_manifest.json"
