import Config

config :dotcom, :cache, Dotcom.Cache.Multilevel

# configured separately so that we can have the health check not require
# SSL
config :dotcom, :secure_pipeline,
  force_ssl: [
    host: nil,
    rewrite_on: [:x_forwarded_proto]
  ]

config :dotcom, DotcomWeb.Endpoint,
  # Enable IPv6 and bind on all interfaces.
  # Set it to {0, 0, 0, 0, 0, 0, 0, 1} for local network only access.
  # See the documentation on https://hexdocs.pm/bandit/Bandit.html#t:options/0
  # for details about using IPv6 vs IPv4 and loopback vs public addresses.m the server machine.
  http: [
    ip: {0, 0, 0, 0, 0, 0, 0, 0},
    # Bandit caps connections beyond `num_connections` * `num_acceptors`. Given
    # our traffic comes in waves (sometimes unpredictably), and we'd rather
    # avoid rejecting traffic, we provision a generous capacity of 70K
    # concurrent connections. This is based on GA data for last season's peak
    # hourly visit count (213,044, April 19 11pm) and average session duration
    # (367 seconds), which results in an estimated mean concurrent connection
    # count of 21,718 with a standard deviation of 147. A worst-case scenario
    # heavy burst in traffic (50% of traffic in 10 min) creates a peak
    # concurrency of ~65K
    thousand_island_options: [
      # The number of acceptor processes to run. Defaults to 100
      # num_acceptors: 100,
      # The maximum number of concurrent connections which each acceptor will
      # accept before throttling connections. Defaults to 16_384
      num_connections: 700
    ],
    http_options: [
      compress: true
    ],
    http_1_options: [
      max_header_length: 16_384,
      max_request_line_length: 16_384
    ]
  ],

  # Finally, we also include the path to a manifest
  # containing the digested version of static files. This
  # manifest is generated by the mix phx.digest task
  # which you typically run after static files are built.
  cache_static_manifest: "priv/static/cache_manifest.json"
