#!/bin/bash
. "$(dirname -- "$0")/_/husky.sh"

# Only save the files that were stagged for the commit
stagged_files=$(git diff --name-only --cached --diff-filter=ACMRTUB)

# formatting
mix format
npm run --prefix apps/site/assets prettier -- -staged

# linting
npm run --prefix apps/site/assets eslint:js
npm run --prefix apps/site/assets eslint:ts

# only re-adds the files that were stagged for the commit
# catching any re-formatted files in the process 
for file in $stagged_files
do
  echo $file
  git add $file
done;
