#!/usr/bin/env bash
# shellcheck disable=SC1091
. "$(dirname -- "$0")/_/husky.sh"

npx --prefix assets lint-staged
npx lint-staged

if [[ `git diff --name-only mix.lock` ]]; then
  git add mix.lock
fi
