name: Push Load Test

on:
  # Invoked via another workflow, value passed in by string
  workflow_call:
    inputs:
      deployment-env:
        description: "Environment to deploy to (dev-green or dev-blue only)"
        required: true
        type: string
        options:
          - dev-green
          - dev-blue
    secrets:
      aws-role-arn:
        required: true
        description: "AWS_ROLE_ARN value"
      aws-account-id:
        required: true
        description: "TID_AWS_ACCOUNT_ID value"

concurrency:
  group: deploy-load-test-${{ inputs.deployment-env }}
  cancel-in-progress: true

jobs:
  check:
    name: Check for changes in load test setup
    runs-on: ubuntu-latest
    needs: validate
    outputs:
      changed: ${{ steps.changes.outputs.load_test == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            load_test:
              - 'deploy/load_test/**'
              - 'integration/load_tests/**'

  push:
    name: Deploy new version
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.changed }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build, tag, and push image to Amazon ECR
        id: ecr
        uses: mbta/actions/build-push-ecr@v2
        with:
          docker-repo: "${{ secrets.aws-account-id || secrets.TID_AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/dotcom-load-tests"
          dockerfile-path: "-f ./deploy/load_test/Dockerfile ."
          role-to-assume: ${{ secrets.aws-role-arn || secrets.AWS_ROLE_ARN }}
