name: Push Monitor

on:
  # UI provided by Github, values populated by repository
  workflow_dispatch:
    inputs:
      deployment-env:
        description: "Environment to deploy to"
        required: true
        type: environment
  # Invoked via another workflow, value passed in by string
  workflow_call:
    inputs:
      deployment-env:
        description: "Environment to deploy to"
        required: true
        type: string
    secrets:
      aws-role-arn:
        required: true
        description: "AWS_ROLE_ARN value"
      aws-account-id:
        required: true
        description: "TID_AWS_ACCOUNT_ID value"

concurrency:
  group: deploy-monitor-${{ inputs.deployment-env }}
  cancel-in-progress: true

jobs:
  check:
    name: Check for changes in monitoring setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      changed: ${{ steps.changes.outputs.monitor == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706 # v4.0.2
        id: changes
        with:
          filters: |
            monitor:
              - 'deploy/monitor/**'
              - 'integration/**'
  push:
    name: Deploy new version
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.changed }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
      - name: Build, tag, and push image to Amazon ECR
        id: ecr
        uses: mbta/actions/build-push-ecr@d37877022d4ae12e96663d2e0a970a5214a2e232 # v2.20
        with:
          docker-repo: "${{ secrets.aws-account-id || secrets.TID_AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/dotcom-monitor"
          dockerfile-path: "-f ./deploy/monitor/Dockerfile ."
          role-to-assume: ${{ secrets.aws-role-arn || secrets.AWS_ROLE_ARN }}
      - name: Deploy Monitor to ${{ inputs.deployment-env }}
        uses: mbta/actions/deploy-ecs@d37877022d4ae12e96663d2e0a970a5214a2e232 # v2.20
        with:
          role-to-assume: ${{ secrets.aws-role-arn || secrets.AWS_ROLE_ARN }}
          ecs-cluster: dotcom
          ecs-service: dotcom-monitor-${{ inputs.deployment-env }}
          docker-tag: ${{ steps.ecr.outputs.docker-tag }}
