name: Remove translation label

on:
  pull_request_review:
    types: [submitted]

permissions:
  issues: write

jobs:
  remove-label:
    if: ${{ github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - name: Remove Not ready for translation label
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            const { owner, repo } = context.repo;
            const issue_number = context.payload.pull_request.number;
            const name = "Not ready for translation";
            const { data: labels } = await github.rest.issues.listLabelsOnIssue({
              owner,
              repo,
              issue_number,
            });

            if (labels.some((label) => label.name === name)) {
              await github.rest.issues.removeLabel({
                owner,
                repo,
                issue_number,
                name,
              });
            }
